/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package adventofcode2023;

import adventofcode2023.days.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        AoCDay d;
        ClassLoader classLoader = Thread.currentThread().getContextClassLoader();
        if (args.length < 1) {
            throw (new Error("No day selected"));
        }
        switch (args[0]) {
            case "1" -> d = new Day01(classLoader.getResourceAsStream("day01"));
            case "2" -> d = new Day02(classLoader.getResourceAsStream("day02"));
            case "3" -> d = new Day03(classLoader.getResourceAsStream("day03"));
            case "4" -> d = new Day04(classLoader.getResourceAsStream("day04"));
            default -> throw(new Error("Not implemented"));
        }

        d.run();
    }
}
